name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # full history required for git push to HF

    - name: Push to Hugging Face Spaces
      run: |
        git remote add hf https://ambruhsia:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/ambruhsia/shl-recommender
        git push hf main --force
